FROM node:18-alpine

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm ci

COPY . .

ARG NEXT_PUBLIC_CAPTCHA_SITE_KEY
ARG NEXT_PUBLIC_BASE_DEV_URL
ARG NEXT_PUBLIC_BASE_TEST_URL

ENV NEXT_PUBLIC_CAPTCHA_SITE_KEY=$NEXT_PUBLIC_CAPTCHA_SITE_KEY
ENV NEXT_PUBLIC_BASE_DEV_URL=$NEXT_PUBLIC_BASE_DEV_URL
ENV NEXT_PUBLIC_BASE_TEST_URL=$NEXT_PUBLIC_BASE_TEST_URL
ENV NEXT_PUBLIC_BASE_URL=$NEXT_PUBLIC_BASE_URL

ENV NODE_ENV production

# ENV NEXT_SHARP_PATH=/node_modules/sharp
ENV NEXT_SHARP_PATH=/tmp/node_modules/sharp

RUN npm run build

EXPOSE  3000

# CMD ["npm", "start"]