export const COUNTRIES = [
	{ value: 'RU', label: 'Россия' },
	{ value: 'AF', label: 'Афганистан' },
	{ value: 'AL', label: 'Албания' },
	{ value: 'DZ', label: 'Алжир' },
	{ value: 'AS', label: 'Американское Самоа' },
	{ value: 'AD', label: 'Андорра' },
	{ value: 'AO', label: 'Ангола' },
	{ value: 'AI', label: 'Ангилья' },
	{ value: 'AQ', label: 'Антарктида' },
	{ value: 'AG', label: 'Антигуа и Барбуда' },
	{ value: 'AR', label: 'Аргентина' },
	{ value: 'AM', label: 'Армения' },
	{ value: 'AW', label: 'Аруба' },
	{ value: 'AU', label: 'Австралия' },
	{ value: 'AT', label: 'Австрия' },
	{ value: 'AZ', label: 'Азербайджан' },
	{ value: 'BS', label: 'Багамские Острова' },
	{ value: 'BH', label: 'Бахрейн' },
	{ value: 'BD', label: 'Бангладеш' },
	{ value: 'BB', label: 'Барбадос' },
	{ value: 'BY', label: 'Беларусь' },
	{ value: 'BE', label: 'Бельгия' },
	{ value: 'BZ', label: 'Белиз' },
	{ value: 'BJ', label: 'Бенин' },
	{ value: 'BM', label: 'Бермудские Острова' },
	{ value: 'BT', label: 'Бутан' },
	{ value: 'BO', label: 'Боливия' },
	{ value: 'BA', label: 'Босния и Герцеговина' },
	{ value: 'BW', label: 'Ботсвана' },
	{ value: 'BR', label: 'Бразилия' },
	{ value: 'BN', label: 'Бруней-Даруссалам' },
	{ value: 'BG', label: 'Болгария' },
	{ value: 'BF', label: 'Буркина-Фасо' },
	{ value: 'BI', label: 'Бурунди' },
	{ value: 'KH', label: 'Камбоджа' },
	{ value: 'CM', label: 'Камерун' },
	{ value: 'CA', label: 'Канада' },
	{ value: 'CV', label: 'Кабо-Верде' },
	{ value: 'KY', label: 'Каймановы Острова' },
	{ value: 'CF', label: 'Центральноафриканская Республика' },
	{ value: 'TD', label: 'Чад' },
	{ value: 'CL', label: 'Чили' },
	{ value: 'CN', label: 'Китай' },
	{ value: 'CO', label: 'Колумбия' },
	{ value: 'KM', label: 'Коморы' },
	{ value: 'CG', label: 'Конго' },
	{ value: 'CD', label: 'Демократическая Республика Конго' },
	{ value: 'CK', label: 'Острова Кука' },
	{ value: 'CR', label: 'Коста-Рика' },
	{ value: 'CI', label: 'Кот-д’Ивуар' },
	{ value: 'HR', label: 'Хорватия' },
	{ value: 'CU', label: 'Куба' },
	{ value: 'CW', label: 'Кюрасао' },
	{ value: 'CY', label: 'Кипр' },
	{ value: 'CZ', label: 'Чешская Республика' },
	{ value: 'DK', label: 'Дания' },
	{ value: 'DJ', label: 'Джибути' },
	{ value: 'DM', label: 'Доминика' },
	{ value: 'DO', label: 'Доминиканская Республика' },
	{ value: 'EC', label: 'Эквадор' },
	{ value: 'EG', label: 'Египет' },
	{ value: 'SV', label: 'Сальвадор' },
	{ value: 'GQ', label: 'Экваториальная Гвинея' },
	{ value: 'ER', label: 'Эритрея' },
	{ value: 'EE', label: 'Эстония' },
	{ value: 'SZ', label: 'Свазиленд' },
	{ value: 'ET', label: 'Эфиопия' },
	{ value: 'FJ', label: 'Фиджи' },
	{ value: 'FI', label: 'Финляндия' },
	{ value: 'FR', label: 'Франция' },
	{ value: 'GF', label: 'Французская Гвиана' },
	{ value: 'PF', label: 'Французская Полинезия' },
	{ value: 'GA', label: 'Габон' },
	{ value: 'GM', label: 'Гамбия' },
	{ value: 'GE', label: 'Грузия' },
	{ value: 'DE', label: 'Германия' },
	{ value: 'GH', label: 'Гана' },
	{ value: 'GI', label: 'Гибралтар' },
	{ value: 'GR', label: 'Греция' },
	{ value: 'GL', label: 'Гренландия' },
	{ value: 'GD', label: 'Гренада' },
	{ value: 'GU', label: 'Гуам' },
	{ value: 'GT', label: 'Гватемала' },
	{ value: 'GN', label: 'Гвинея' },
	{ value: 'GW', label: 'Гвинея-Бисау' },
	{ value: 'GY', label: 'Гайана' },
	{ value: 'HT', label: 'Гаити' },
	{ value: 'VA', label: 'Ватикан' },
	{ value: 'HN', label: 'Гондурас' },
	{ value: 'HK', label: 'Гонконг' },
	{ value: 'HU', label: 'Венгрия' },
	{ value: 'IS', label: 'Исландия' },
	{ value: 'IN', label: 'Индия' },
	{ value: 'ID', label: 'Индонезия' },
	{ value: 'IR', label: 'Иран' },
	{ value: 'IQ', label: 'Ирак' },
	{ value: 'IE', label: 'Ирландия' },
	{ value: 'IL', label: 'Израиль' },
	{ value: 'IT', label: 'Италия' },
	{ value: 'JM', label: 'Ямайка' },
	{ value: 'JP', label: 'Япония' },
	{ value: 'JO', label: 'Иордания' },
	{ value: 'KZ', label: 'Казахстан' },
	{ value: 'KE', label: 'Кения' },
	{ value: 'KI', label: 'Кирибати' },
	{ value: 'KW', label: 'Кувейт' },
	{ value: 'KG', label: 'Киргизия' },
	{ value: 'LA', label: 'Лаос' },
	{ value: 'LV', label: 'Латвия' },
	{ value: 'LB', label: 'Ливан' },
	{ value: 'LS', label: 'Лесото' },
	{ value: 'LR', label: 'Либерия' },
	{ value: 'LY', label: 'Ливия' },
	{ value: 'LI', label: 'Лихтенштейн' },
	{ value: 'LT', label: 'Литва' },
	{ value: 'LU', label: 'Люксембург' },
	{ value: 'MO', label: 'Макао' },
	{ value: 'MK', label: 'Северная Македония' },
	{ value: 'MG', label: 'Мадагаскар' },
	{ value: 'MW', label: 'Малави' },
	{ value: 'MY', label: 'Малайзия' },
	{ value: 'MV', label: 'Мальдивы' },
	{ value: 'ML', label: 'Мали' },
	{ value: 'MT', label: 'Мальта' },
	{ value: 'MH', label: 'Маршалловы Острова' },
	{ value: 'MR', label: 'Мавритания' },
	{ value: 'MU', label: 'Маврикий' },
	{ value: 'MX', label: 'Мексика' },
	{ value: 'FM', label: 'Микронезия' },
	{ value: 'MD', label: 'Молдова' },
	{ value: 'MC', label: 'Монако' },
	{ value: 'MN', label: 'Монголия' },
	{ value: 'ME', label: 'Черногория' },
	{ value: 'MA', label: 'Марокко' },
	{ value: 'MZ', label: 'Мозамбик' },
	{ value: 'MM', label: 'Мьянма' },
	{ value: 'NA', label: 'Намибия' },
	{ value: 'NR', label: 'Науру' },
	{ value: 'NP', label: 'Непал' },
	{ value: 'NL', label: 'Нидерланды' },
	{ value: 'NC', label: 'Новая Каледония' },
	{ value: 'NZ', label: 'Новая Зеландия' },
	{ value: 'NI', label: 'Никарагуа' },
	{ value: 'NE', label: 'Нигер' },
	{ value: 'NG', label: 'Нигерия' },
	{ value: 'NU', label: 'Ниуэ' },
	{ value: 'KP', label: 'КНДР' },
	{ value: 'NO', label: 'Норвегия' },
	{ value: 'OM', label: 'Оман' },
	{ value: 'PK', label: 'Пакистан' },
	{ value: 'PW', label: 'Палау' },
	{ value: 'PS', label: 'Палестина' },
	{ value: 'PA', label: 'Панама' },
	{ value: 'PG', label: 'Папуа - Новая Гвинея' },
	{ value: 'PY', label: 'Парагвай' },
	{ value: 'PE', label: 'Перу' },
	{ value: 'PH', label: 'Филиппины' },
	{ value: 'PN', label: 'Питкэрн' },
	{ value: 'PL', label: 'Польша' },
	{ value: 'PT', label: 'Португалия' },
	{ value: 'PR', label: 'Пуэрто-Рико' },
	{ value: 'QA', label: 'Катар' },
	{ value: 'RO', label: 'Румыния' },
	{ value: 'RW', label: 'Руанда' },
	{ value: 'BL', label: 'Сен-Бартелеми' },
	{ value: 'SH', label: 'Острова Святой Елены, Вознесения и Тристан-да-Кунья' },
	{ value: 'KN', label: 'Сент-Китс и Невис' },
	{ value: 'LC', label: 'Сент-Люсия' },
	{ value: 'MF', label: 'Сен-Мартен' },
	{ value: 'PM', label: 'Сен-Пьер и Микелон' },
	{ value: 'VC', label: 'Сент-Винсент и Гренадины' },
	{ value: 'WS', label: 'Самоа' },
	{ value: 'SM', label: 'Сан-Марино' },
	{ value: 'ST', label: 'Сан-Томе и Принсипи' },
	{ value: 'SA', label: 'Саудовская Аравия' },
	{ value: 'SN', label: 'Сенегал' },
	{ value: 'RS', label: 'Сербия' },
	{ value: 'SC', label: 'Сейшельские Острова' },
	{ value: 'SL', label: 'Сьерра-Леоне' },
	{ value: 'SG', label: 'Сингапур' },
	{ value: 'SK', label: 'Словакия' },
	{ value: 'SI', label: 'Словения' },
	{ value: 'SB', label: 'Соломоновы Острова' },
	{ value: 'SO', label: 'Сомали' },
	{ value: 'ZA', label: 'Южно-Африканская Республика' },
	{ value: 'KR', label: 'Республика Корея' },
	{ value: 'SS', label: 'Южный Судан' },
	{ value: 'ES', label: 'Испания' },
	{ value: 'LK', label: 'Шри-Ланка' },
	{ value: 'SD', label: 'Судан' },
	{ value: 'SR', label: 'Суринам' },
	{ value: 'SE', label: 'Швеция' },
	{ value: 'CH', label: 'Швейцария' },
	{ value: 'SY', label: 'Сирия' },
	{ value: 'TW', label: 'Тайвань' },
	{ value: 'TJ', label: 'Таджикистан' },
	{ value: 'TZ', label: 'Танзания' },
	{ value: 'TH', label: 'Таиланд' },
	{ value: 'TL', label: 'Тимор-Лешти' },
	{ value: 'TG', label: 'Того' },
	{ value: 'TO', label: 'Тонга' },
	{ value: 'TT', label: 'Тринидад и Тобаго' },
	{ value: 'TN', label: 'Тунис' },
	{ value: 'TR', label: 'Турция' },
	{ value: 'TM', label: 'Туркменистан' },
	{ value: 'TC', label: 'Острова Теркс и Кайкос' },
	{ value: 'TV', label: 'Тувалу' },
	{ value: 'UG', label: 'Уганда' },
	{ value: 'UA', label: 'Украина' },
	{ value: 'AE', label: 'Объединенные Арабские Эмираты' },
	{ value: 'GB', label: 'Соединенное Королевство' },
	{ value: 'US', label: 'Соединенные Штаты Америки' },
	{ value: 'UY', label: 'Уругвай' },
	{ value: 'UZ', label: 'Узбекистан' },
	{ value: 'VU', label: 'Вануату' },
	{ value: 'VE', label: 'Венесуэла' },
	{ value: 'VN', label: 'Вьетнам' },
	{ value: 'VG', label: 'Виргинские Острова (Великобритания)' },
	{ value: 'VI', label: 'Виргинские Острова (США)' },
	{ value: 'WF', label: 'Уоллис и Футуна' },
	{ value: 'EH', label: 'Западная Сахара' },
	{ value: 'YE', label: 'Йемен' },
	{ value: 'ZM', label: 'Замбия' },
	{ value: 'ZW', label: 'Зимбабве' },
];
