export const skills = [
	{ value: 'react', label: 'React' },
	{ value: 'redux', label: 'Redux' },
	{ value: 'typescript', label: 'TypeScript' },
	{ value: 'adobe-xd', label: 'Adobe XD' },
	{ value: 'sketch', label: 'Sketch' },
	{ value: 'figma', label: 'Figma' },
	{ value: 'testrail', label: 'TestRail' },
	{ value: 'jira', label: 'Jira' },
	{ value: 'selenuim', label: 'Selenium' },
	{ value: 'trello', label: 'Trello' },
	{ value: 'asana', label: 'Asana' },
	{ value: 'microsoft-project', label: 'Microsoft Project' },
	{ value: 'use-case-diagrams', label: 'Use case diagrams' },
	{ value: 'flowcharts', label: 'Flowcharts' },
	{ value: 'data-modeling-tools', label: 'Data modeling tools' },
	{ value: 'jenkins', label: 'Jenkins' },
	{ value: 'docker', label: 'Docker' },
	{ value: 'ansible', label: 'Ansible' },
];
